---
title: "International Vistor Arrivals Statistics - `r format(Sys.Date(), '%B %Y')` Highlights"
output: 
  word_document:
    reference_docx: styles_reference.docx
---

```{r setup, include=FALSE}
# Set echo=FALSE as default for code cells
knitr::opts_chunk$set(echo = FALSE, 
                      warning = FALSE,
                      dpi = 600)
```

```{r preparation, include = FALSE}
# Load the required libraries
library(knitr) # Creating documents
library(flextable) # Nicely formatted tables
library(rnaturalearth) # World map
library(sf) # Working with spatial data
library(ggplot2) # Creating plots
library(dplyr) # Working with data
library(tidyr) # For pivoting data.frames
library(janitor) # Adding row and column totals

# Set the table formatting defaults
set_flextable_defaults(font.family="Times New Roman", font.size=5, font.color="black",
                       text.align="left", table.layout="fixed", theme_fun="theme_booktabs")

# Note where VNSO code/data is on current computer
repository <- file.path("..", "..")

# Note the open data path
openDataFolder <- file.path(repository, "data", "open")

# Note the secure data path
secureDataFolder <- file.path(repository, "data", "secure")

# Some general ggplot settings
plotTextSize <- 9
xAxisText <- list(
  "angle" = 35,
  "size" = plotTextSize,
  "vjust" = 1.1,
  "hjust" = 1
)
```


```{r load data}

# Load the processed trade statistics for month of interest
# Read in the processed TOURISM data from secure folder of the repository 
tourismProcessedFile <- file.path(secureDataFolder, "OUT_PROC_ASY_ProcessedRawData_31.12.19.csv")
tourismProcessed <- read.csv(tourismProcessedFile, header = TRUE, na.strings = c("","NA","NULL","null"))

# Get the current month and year of data
currentMonth <- unique(tourismProcessed$Month)
currentYear <- unique(tourismProcessed$Year)
```


# National Sustainable Development Plan Indicators (NSDP)

```{r NSDP indicators}
### Calculating NSDP Indicators

# ECO 3.2.1 Average annual household income from tourism

# Calculate NSDP indicator
indicatorENV1.3.1<- (sum(importSubstitutionDataFrame$Stat..Value))

# ECO 3.2.2 Annual change in tourism by air and sea arrivals

# ECO 3.2.3 Proportion of visitors traveling to outer islands


```


```{r NSDP table}

# Create the NSDP table
nsdpIndicators <- data.frame(
  "Policy Objectives"=c("ENV 1.3: Reduce reliance on food imports through import substitution for food products that can be produced domestically",
                        "ECO 1.5: Increase access to markets for Vanuatu exports",
                        "ECO 1.5: Increase access to markets for Vanuatu exports",
                        "ECO 1.6: Require all new trade agreements to demonstrate tangible benefits in the national interest",
                        "ECO 1.7: Stimulate economic diversification to spread the benefits of growth and increase economic stability",
                        "ECO 4.3: Increase production and processing of niche commodities, and value addition to commodities in which Vanuatu enjoys a comparative advantage"),
  "SMART Indicators"=c("ENV 1.3.1 Total annual volume of imports of food and products targeted by DARD as those that can be produced domestically (including ‘value-added products)",
                       "ECO 1.5.2 Trade by trade agreement (value)",
                       "ECO 1.5.3 Balance of trade by major partner countries",
                       "ECO 1.6.2 Total estimated value of trade agreement as proportion of GDP",
                       "ECO 1.7.1 Level of production of major commodities to include cocoa and copra",
                       "ECO 4.3.2 Ratio of processed export commodities (including coconut, kava, cocoa, coffee) to raw exports"),
  "Indicator Value"= c(
    indicatorENV1.3.1,
    indicatorECO1.5.2,
    indicatorECO1.5.3,
    indicatorECO1.6.2,
    indicatorECO1.7.1,
    indicatorECO4.3.2
  ),check.names=FALSE, stringsAsFactors=FALSE)


# Round the indicator values
nsdpIndicators$`Indicator Value` <- round(nsdpIndicators$`Indicator Value`, digits = 2)

# Initiailise a flextable object for NSDP table
indicatorsTable <- flextable(nsdpIndicators)

# Add a header row and set background colour
indicatorsTable <- bg(indicatorsTable, bg="coral1", part="header")

# Set the vertical alignment to top
indicatorsTable <- valign(indicatorsTable, valign="top", part="all")

# Merge repeated values in the Policy Objectives column
indicatorsTable <- merge_v(indicatorsTable, j = "Policy Objectives")

# Set table width to 100%
indicatorsTable <- set_table_properties(indicatorsTable, width=1, layout="autofit")

# Set the theme
indicatorsTable <- theme_booktabs(indicatorsTable)

# Print table
indicatorsTable
```
 
&nbsp;  
&nbsp;  
&nbsp;  
&nbsp;  
&nbsp;  
&nbsp;  
&nbsp;  
&nbsp;  

# Visitor Arrivals by Usual Country of Residence

```{r major partner country trade, warning=FALSE, fig.width=5.5, fig.height=2.5}

## Getting latest statistics ##

countryVistorsGrouped <- tourismProcessed %>%
  filter(PORT %in% c("SAIR","SAIRP","VAIR","VAIRP"))%>%
  filter(VisitorResident %in% ("Visitor"))%>%
  filter(ARR.DEPART %in%("ARRIVAL"))%>%
  group_by(Country.or.Area.x) %>%
  count()

# Drop Vanuatu
countryVisitedNoVanuatu <- countryVistorsGrouped %>%
  filter(Country.or.Area.x != "Vanuatu")

# Order table by the country with most visitor
countryVisitedOrdered <- countryVisitedNoVanuatu %>%
  arrange(desc(n))
colnames(countryVisitedOrdered)[1] <- "Country"

# Get the polygons for the world
world <- rnaturalearth::ne_countries(type = "countries", scale = "medium", returnclass = "sf")

# Merge in my example data
world <- merge(world, countryVisitedOrdered, by.x = "admin", by.y = "Country", all.x = TRUE)

# Plot with ggplot
ggplot(data = world) +
  geom_sf(aes(fill = countryVisitedOrdered)) + 
  guides(fill=guide_legend(title="Visitor Arrivals by Usual Country of Residence\n(number)")) +
  theme(legend.title = element_text(size = 9))

```



